### ISSUE TITLE
Consider utilizing Fabric/Quilt Dependency Overrides

### ISSUE THREAD

**Issue by notabirb1** [intergrav/additive#28]
There are a few mods that seem like they may not update to 1.20/1.20.1 (Smooth Boot in particular). One way to use these mods on 1.20 sooner would be [Fabric Dependency Overrides](https://fabricmc.net/wiki/tutorial:dependency_overrides) and [Quilt Dependency Overrides](https://github.com/QuiltMC/quilt-loader/wiki/Dependency-Overrides), which allow skipping the dependency checks for a mod, including the check for the current Minecraft version. In my testing, Smooth Boot (1.19.4) worked well on 1.20/1.20.1 via overrides, and Borderless Mining & Animatica may work this way as well. 
I've also seen a few other popular performance modpacks use this to speed up their update process (Fabulously Optimized uses them, that's actually how I found out about the overrides.)

Using the dependency overrides could be a little risky / unstable, but it might be the only way to use some mods on 1.20/1.20.1 if they don't get updated (and if they do, the dependency overrides could help get the mods working sooner.)

**Comment by intergrav** [comment]
I’ve said in the past on the discord server that I typically prefer not to use overrides as it goes against what the mod author thinks their mod is supported on, so it can lead to bugs and other issues, but I was considering making an override for Smooth Boot if no alternative comes out or the mod author chooses not to change the fabric mod json’s version since thread priorities can be somewhat important for some lower-end machines

**Comment by notabirb1** [comment]
Ok, that's understandable. Although Smooth Boot's thread priority changes might be better for a separate mod, since its original purpose was to speed up Minecraft's loading.

**Comment by intergrav** [comment]
forgot to mention, we made [ThreadTweak](https://modrinth.com/mod/threadtweak) as an alternative to Smooth Boot for later Minecraft versions so dependency overrides are no longer needed for now
